### ISSUE TITLE
Optional parameters are being set to required

### ISSUE THREAD

**Issue by richarddavenport** [byme8/ZeroQL#42]
**Describe the bug**
The generated query is marking a variable as required, but the schema is optional.

**How to Reproduce**

**Expected behavior**
The optional parameter shouldn't be marked as required. Ultimately I'd like to be able to _not_ include limit and offset, but c# is yelling at me.

**Screenshots**
Generated Query:
<img width="1294" alt="Screenshot 2023-05-18 at 5 35 43 PM" src="https://github.com/byme8/ZeroQL/assets/3596012/9f3f5fff-37af-4beb-8954-5925351e06bf">

Source Code:
<img width="1495" alt="Screenshot 2023-05-18 at 5 38 13 PM" src="https://github.com/byme8/ZeroQL/assets/3596012/7d5f7a00-a509-47ce-abd7-13862d360991">

Implementation:
<img width="974" alt="Screenshot 2023-05-18 at 5 39 14 PM" src="https://github.com/byme8/ZeroQL/assets/3596012/f9a63520-09fc-4c2c-b35f-bd766366d502">

**Environment (please complete the following information):**
 - Nuget version [3.6.2]
 - IDE: [VS Code]
 - .Net Version [6.0.400]

**Comment by byme8** [comment]
Yeah nice point. I will have a look.

**Comment by byme8** [comment]
Checkout v4.0.0-preview.4. Now, parameters defined in GraphLQ schema as nullable are optional. However, on the C# level, it is a bit messy. In GraphQL, you need to specify every parameter by name. As a result, their order doesn't matter. In C#, order matters when you pass parameters without names. So, now in C#, every parameter is optional, but ZeroQL additionally tracks which one is really optional and which one doesn't. Don't be afraid when you see something like that:
```
[ZeroQL.GraphQLFieldSelector("usersIds")]
public int[] UsersIds(UserKind? kind = default !, int page = default !, int? size = default !, string? filter = default !, int[]? ids = default !)
{
    return __UsersIds;
}
```

**Comment by byme8** [comment]
I will thnk how to make it better, but for now I don't a better option.

**Comment by richarddavenport** [comment]
@byme8 Thank you, I'll give it a shot! I tend to use named parameters anyways, so this is great. I'll let you know how it goes!

**Comment by richarddavenport** [comment]
I installed `4.0.0-preview.4` and my generated code looks like this:  
<img width="1251" alt="Screenshot 2023-05-22 at 7 43 43 AM" src="https://github.com/byme8/ZeroQL/assets/3596012/ee3eee1d-ff50-42bb-8631-9ddfcf40568a">

Am I doing something wrong?

**Comment by byme8** [comment]
Have you updated CLI in .config/dotnet-tools.json?

**Comment by richarddavenport** [comment]
@byme8  Thanks! :face_palm: forgot about that.

**Comment by richarddavenport** [comment]
Sorry for the bad image, not sure how to show you the problem. I am on the latest release.

It looks like it doesn't like my named parameters, and it still requires me to put something in the parameters I don't need.
<img width="1206" alt="Screenshot 2023-05-22 at 1 46 11 PM" src="https://github.com/byme8/ZeroQL/assets/3596012/60e7d5b1-894b-4720-bc1b-44c64cf38514">

Maybe I need to write it differently?

**Comment by byme8** [comment]
The issue with `` (selector: ) `` is fixed in 4.0.0-preview.5. However, it is not clear where you get all other parameters like `` $objects:[userFlowItem_insert_input!]! ``, `` $limit: Int! ``, and so on. First of all, they are not nullable, if the schema is correct. It means that they are required. You should get a compilation error. I see that you a using the VS Code for development. It can be somehow related. I will do more tests later on.

**Comment by richarddavenport** [comment]
Thanks! I tried preview.5 and I was left with `()` instead of `(selector: )`.

**Comment by richarddavenport** [comment]
Sorry, my last comment was probably not clear. If I'm left with only `()` it is an invalid query.

I'm still not totally sure I understand why the parameters are being generated the way they are.
In this example `$offset` is optional, but in the parameters it's marked required. This query is valid, but it _forces_ me to add a parameter like offset, even though I don't use it. I just set it to 0 to make the code compile.

```gql
query ($where: flowItem_bool_exp!, $offset: Int!) {
  selectFlowItems(offset: $offset, where: $where) {
    id
    flowItemType {
      enumValue
    }
    userFlowItems(offset: $offset) {
      id
      expirationDatetime
      flowItem {
        flowItemType {
          enumValue
        }
      }
      userFlowItemMfas(offset: $offset) {
        id
        code
      }
    }
  }
}
```
<img width="964" alt="Screenshot 2023-05-22 at 9 47 27 PM" src="https://github.com/byme8/ZeroQL/assets/3596012/ad469fdf-b40a-41d7-8e4d-77cfb1629231">

Here is the query without the `$offset`:
```gql
query ($where: flowItem_bool_exp!) {
  selectFlowItems(where: $where) {
    id
    flowItemType {
      enumValue
    }
    userFlowItems() {
      id
      expirationDatetime
      flowItem {
        flowItemType {
          enumValue
        }
      }
      userFlowItemMfas() {
        id
        code
      }
    }
  }
}
```
While this helps without forcing me to add `$offset` the problem is that this is an invalid query at `userFlowItems()` and `userFlowItemMfas()`.

The query in this test file is invlid: https://github.com/byme8/ZeroQL/blob/main/src/ZeroQL.Tests/SourceGeneration/QueryTests.SupportsOptionalArgumentsWithOnlySelector.verified.txt#L2

**Comment by byme8** [comment]
> The query in this test file is invalid:

What provider do you use for your GraphQL server? This query works fine with HotChocolate.

**Comment by byme8** [comment]
Version 4.0.0-preview.6 will not generate `` () `` for a query without arguments.
