### ISSUE TITLE
Suffix 'ZeroQL' added to a single type's name on build, results in error CS0246

### ISSUE THREAD

**Issue by Eraph** [byme8/ZeroQL#81]
**Describe the bug**
Building from a fresh `schema fetch` results in the following error from `obj/ZeroQL/config.zeroql.json.g.cs`:
> The type or namespace name 'TimeWorked' could not be found (are you missing a  
using directive or an assembly reference?)

The build process has created a type called `TimeWorkedZeroQL`, but no references to that type include that suffix. The schema does _not_ include the suffix anywhere. This only happens for this type in the schema, other types are unaffected.

**How to Reproduce**
Pull the schema and build the project.

**Expected behavior**
There should be no errors on build; types should not have the suffix `ZeroQL` attached to them.

**Environment (please complete the following information):**
 - Nuget package version: v6.1.0 (CLI)
 - IDE: VS Code, CLI run in terminal
 - .Net Version: 8.0.100-rc.2.23502.2

**Additional context**
There is a property in `TimeWorked` of type `string?` with the name `TimeWorked`, could this be causing a bit of confusion?
This problem can be temporarily fixed by manually removing the suffix from the type name, but as the `obj` directory isn't committed to Git, this change is not persisted. Subsequent builds don't seem to modify the file, presumably until the schema changes.

**Comment by Eraph** [comment]
Apologies, this _isn't_ fixed by removing the suffix because it generates a CS0542 error in this case (member names cannot be the same as their enclosing type). This makes sense, the suffix is there to prevent this problem.

Seems the real problem lies in a property (that is, with a getter and a setter) is not being given the correct type:

``` csharp
public TimeWorked[]? __Results { get; set; }
```

**Comment by byme8** [comment]
Can you post a part of the schema that fails? I have tried to reproduce but have not been able to.

**Comment by Eraph** [comment]
```
type TimeWorked implements Node {
  id: ID!
  ...
  timeWorked: String
  ...
}
```

And further down:
```
type TimeWorkedSearchResults {
  results: [TimeWorked!]
}
```

**Comment by byme8** [comment]
Checkout v6.1.1-preview.2. The issue should be fixed.

**Comment by Eraph** [comment]
No dice. I've updated the Nuget package, removed the `schema.graphql` file and `config.zeroql.json.g.cs` files, pulled the schema and attempted a rebuild, still getting the issue.

I've managed to distill the problem into a simple `schema.graphql` file that will replicate the problem. You should be able to build a project with this in it and see how it fails. I hope this helps diagnose it!

```
type TimeWorked {
  timeWorked: String
}

type TimeWorkedSearchResults {
  results: [TimeWorked!]
}
```

**Comment by byme8** [comment]
Have you updated the ZeroQL CLI? It is responsible for initial generation.

**Comment by Eraph** [comment]
That's the missing trick! Works perfectly, thank you so much for fixing this so quickly.
